Recipe book
Sinytra/Connector pull request #113
Opened 2023-08-25 09:50 UTC by melontini

Hello, this PR is related to #103, but I completely changed the implementation due to a little issue.

I tested it with RBIP and it works correctly.

The patch is pretty simple, and I also added comments, but as a gist:

- We reset `RecipeBookCategories.AGGREGATE_CATEGORIES` to vanilla values.
- We inject at the `TAIL` of `RecipeBookManager.init()` to merge any categories that may have been added by fabric mods.
- We set `RecipeBookCategories.AGGREGATE_CATEGORIES` to `RecipeBookManager.AGGREGATE_CATEGORIES`.

This *should* account for most additions. Everything else works as is.

2023-08-25 12:50 UTC, melontini commented
Btw, since Forge's event doesn't support modifying existing categories ([Unless you do this, lol](https://github.com/melontini/recipe_book_is_pain/blob/688e5f3464b3c96f713494d54b0836d742e3606c/src/main/java/me/melontini/recipebookispain/RecipeBookIsPain.java#L47)), it might be better to just insert merged categories at their index.

2023-08-26 09:18 UTC, Su5eD requested changes
I've tested this and it works as expected. Just needs some minor style/structure changes, but otherwise it's good to go.

2023-08-26 09:18 UTC, Su5eD commented on src/mod/java/dev/su5ed/sinytra/connector/mod/mixin/RecipeBookCategoriesMixin.java
> +
Code style: no newline at the end of class
```suggestion
```

2023-08-26 09:18 UTC, Su5eD commented on src/mod/java/dev/su5ed/sinytra/connector/mod/mixin/RecipeBookManagerMixin.java
> +
Code style: no newline at the end of class
```suggestion
```

2023-08-26 09:18 UTC, Su5eD commented on src/mod/java/dev/su5ed/sinytra/connector/mod/mixin/RecipeBookManagerMixin.java
> +
Code style: no newline before first field
```suggestion
```

2023-08-26 09:18 UTC, Su5eD commented on src/mod/resources/connectormod.mixins.json
> +    "RecipeBookCategoriesAccessor"
Can we move these to their own `recipebook` subpackage to better keep track of the patch's changes?

2023-08-26 09:26 UTC, Su5eD approved these changes

2023-08-26 09:28 UTC, merged